# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ips_blink_rx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ips_blink_rx.proto\"y\n\rSignalQuality\x12\x14\n\x0c\x63lock_offset\x18\x01 \x01(\x01\x12\x10\n\x08\x66p_index\x18\x03 \x01(\x02\x12\x12\n\nfp_to_peak\x18\x04 \x01(\x02\x12\n\n\x02mc\x18\x05 \x01(\x02\x12\x0f\n\x07rssi_rx\x18\x07 \x01(\x02\x12\x0f\n\x07rssi_fp\x18\x08 \x01(\x02\"@\n\x0cSignalRxInfo\x12\x0f\n\x07rx_time\x18\x01 \x01(\x04\x12\x1f\n\x07quality\x18\x02 \x01(\x0b\x32\x0e.SignalQuality\"\x9c\x02\n\x0e\x42linkRxDataMsg\x12\x0e\n\x06tag_id\x18\x01 \x01(\x06\x12\x11\n\tblink_cnt\x18\x02 \x01(\r\x12.\n\x08rx_infos\x18\x03 \x03(\x0b\x32\x1c.BlinkRxDataMsg.RxInfosEntry\x12\x0c\n\x04time\x18\x04 \x01(\x06\x12)\n\x05\x64ises\x18\x05 \x03(\x0b\x32\x1a.BlinkRxDataMsg.DisesEntry\x12\x11\n\tis_moving\x18\x06 \x01(\x08\x1a=\n\x0cRxInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\x06\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.SignalRxInfo:\x02\x38\x01\x1a,\n\nDisesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x06\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ips_blink_rx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLINKRXDATAMSG_RXINFOSENTRY._options = None
  _BLINKRXDATAMSG_RXINFOSENTRY._serialized_options = b'8\001'
  _BLINKRXDATAMSG_DISESENTRY._options = None
  _BLINKRXDATAMSG_DISESENTRY._serialized_options = b'8\001'
  _SIGNALQUALITY._serialized_start=22
  _SIGNALQUALITY._serialized_end=143
  _SIGNALRXINFO._serialized_start=145
  _SIGNALRXINFO._serialized_end=209
  _BLINKRXDATAMSG._serialized_start=212
  _BLINKRXDATAMSG._serialized_end=496
  _BLINKRXDATAMSG_RXINFOSENTRY._serialized_start=389
  _BLINKRXDATAMSG_RXINFOSENTRY._serialized_end=450
  _BLINKRXDATAMSG_DISESENTRY._serialized_start=452
  _BLINKRXDATAMSG_DISESENTRY._serialized_end=496
# @@protoc_insertion_point(module_scope)
