name: Python application

on:
  push:
   branches: ["main"]
   tags:        
      - v1.0.0
      - v1.0.0.*

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest,macos-10.15,ubuntu-20.04]
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
       #安装python
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9.13'
        
       #安装pip以及安装第三方库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./test.proto
            
       
       #单元测试
      - name: test
        run: python -m unittest  test_main.py 
     
       #pyinstaller打包test.py
      - name: pyinstaller package
        if: ${{github.ref_type}} =='tag'
        run: pyinstaller  -F main.py -n ${{ runner.os }}_test
          
       #上传文件
      - name: Upload Artifacts
        if: ${{github.ref_type}} =='tag'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} pyinstaller
          path: ./dist
          
      - name: download-artifact   
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v3
        with: 
          path: ./artifact
 
       #发布文件  
      - name: Create Release and Upload Release Asset
        if: ${{github.ref_type}} =='tag'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{github.ref_name}}
          automatic_release_tag: ${{github.ref_name}}
          files: ./artifact

            
