
name: Python application

on:
  push:
   branches: ["main"]
   tags: 
     - v[0-9]+.[0-9]+
     - v[0-9]+.[0-9]+.[0-9]+
     - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
     

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9.13'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./test.proto
          python main.py
            
      - name: pytest
        run: pytest  test_main.py 
     
      
      - name: nuitka package
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          standalone: true
          enable-plugins: numpy
          
#       - name: note
#         if: github.ref_type=='tag'
#         shell: python 
#         run: |
#           import json;import os;f=open('releasenotes.json',"r");obj=json.load(f);note=[i['notes'] for i in obj['tags_releasenotes'] if i['name']=='${{github.ref_name}}'];f.close();note=[note[0] if note else ''][0];
#           os.system("echo 'NOTE<<EOF' >> $GITHUB_ENV")
#           tmp=[os.system("echo '{}' >> $GITHUB_ENV".format(n)) for n in note]
#           os.system("echo 'EOF' >> $GITHUB_ENV")

      - name: Upload Artifacts
        if: github.ref_type=='tag' 
        uses: actions/upload-artifact@v3
        with:
           name: ${{ runner.os }}_pyinstaller
           path: .
          
#       - name: download-artifact   
#         if: github.ref_type=='tag'
#         uses: actions/download-artifact@v3
#         with: 
#           path: ./artifact
          
#       - name: Create Release
#         if: github.ref_type=='tag' 
#         uses: softprops/action-gh-release@v1
#         with:
#           tag_name: ${{github.ref_name}}
#           name: ${{github.ref_name}}
#           body: ${{env.NOTE}}
#           prerelease: false
#           draft: false
#           files: ./artifact/${{ runner.os }}_pyinstaller/*


